name: Build release binary on ubuntu-latest to be used for other actions

on: [ workflow_dispatch ]

jobs:
  build-ubnutu-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: "Install tools"
      run: sudo apt-get install -y libgdbm-dev libmbedtls-dev
    - name: "Build"
      run: |
        curl -f -o get-gauche.sh https://raw.githubusercontent.com/shirok/get-gauche/master/get-gauche.sh
        chmod +x get-gauche.sh
        ./get-gauche.sh --prefix /usr --destdir package --version latest --force
        (cd package; tar czvf ../gauche-binary-ubuntu-latest.tar.gz .)
    - name: "Upload"
      run: |
        gh release upload v1 gauche-binary-ubuntu-latest.tar.gz --clobber
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
