name: Build release binary to be used for other actions

on: [ workflow_dispatch ]

jobs:
  trigger-tester:
    runs-on: ubuntu-latest
    steps:
    - name: "Install tools"
      run: sudo apt-get install -y libgdbm-dev libmbedtls-dev
    - name: "Build"
      run: |
        curl -f -o get-gauche.sh https://raw.githubusercontent.com/shirok/get-gauche/master/get-gauche.sh
        chmod +x get-gauche.sh
        ./get-gauche.sh --prefix /usr --destdir package --version latest --force
        (cd package; tar czvf ../gauche-binary-ubuntu-latest.tar.gz .)
