name: Build release binary to be used for other actions

on: [ workflow_dispatch ]

jobs:
  trigger-tester:
    runs-on: ubuntu-latest
    steps:
    - name: "Install tools"
      run: sudo apt-get install -y libgdbm-dev libmbedtls-dev
    - name: "Build"
      run: |
        ./build-binary-tarball.sh
